apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: apitestn
  title: API TEST T
  description: API TEST D
  tags:
    - api 
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Application
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Repo name
          default: my-liberty-app
          ui:field: EntityNamePicker
          maxLength: 23  

  steps:
    - id: log-var
      name: Log the var
      action: debug:log
      input:
        # Safer approach using config
        message: "My callback URL is: ${{ secrets.AUTH_GITHUB_CALLBACK_URL }}" 

  
