apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: apitestn
  title: API TEST T
  description: API TEST D
  tags:
    - api 
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Instana Configuration
      required:
        - applicationName
        - serviceName
      properties:
        applicationName:
          title: Application Name
          type: string
          description: The name to display in Instana
          ui:autofocus: true
        serviceName:
          title: Kubernetes Service Name
          type: string
          description: The service name to monitor (matches kubernetes.service.name) 

  steps:
    - id: create-instana-monitoring
      name: Create Instana Monitoring
      action: http:backstage:request
      input:
        method: POST
        path: /proxy/dream/api/application-monitoring/settings/application  
        headers:
          content-type: 'application/json'
        body:
          label: ${{ parameters.applicationName }}
          scope: INCLUDE_ALL_DOWNSTREAM
          boundaryScope: ALL
          builtInAlertIds: []
          tagFilterExpression:
            type: TAG_FILTER
            name: kubernetes.service.name
            operator: EQUALS
            entity: DESTINATION
            value: ${{ parameters.serviceName }} 
    - id: log
      name: LOG ID
      action: debug:log
      input: 
        message: "Hello the id is ${{ steps.create-instana-monitoring.output.body.id }}"



      
